/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DagRouteImport } from './routes/dag'
import { Route as ImporterenRouteImport } from './routes/importeren'
import { Route as InstellingenRouteImport } from './routes/instellingen'
import { Route as KlantenRouteImport } from './routes/klanten'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PrintenRouteImport } from './routes/printen'
import { Route as PrullenbakRouteImport } from './routes/prullenbak'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UitnodigingRouteImport } from './routes/uitnodiging'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DagRoute = DagRouteImport.update({
  id: '/dag',
  path: '/dag',
  getParentRoute: () => rootRouteImport,
} as any)
const ImporterenRoute = ImporterenRouteImport.update({
  id: '/importeren',
  path: '/importeren',
  getParentRoute: () => rootRouteImport,
} as any)
const InstellingenRoute = InstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => rootRouteImport,
} as any)
const KlantenRoute = KlantenRouteImport.update({
  id: '/klanten',
  path: '/klanten',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintenRoute = PrintenRouteImport.update({
  id: '/printen',
  path: '/printen',
  getParentRoute: () => rootRouteImport,
} as any)
const PrullenbakRoute = PrullenbakRouteImport.update({
  id: '/prullenbak',
  path: '/prullenbak',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UitnodigingRoute = UitnodigingRouteImport.update({
  id: '/uitnodiging',
  path: '/uitnodiging',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dag': typeof DagRoute
  '/importeren': typeof ImporterenRoute
  '/instellingen': typeof InstellingenRoute
  '/klanten': typeof KlantenRoute
  '/login': typeof LoginRoute
  '/planning': typeof PlanningRoute
  '/printen': typeof PrintenRoute
  '/prullenbak': typeof PrullenbakRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/uitnodiging': typeof UitnodigingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dag': typeof DagRoute
  '/importeren': typeof ImporterenRoute
  '/instellingen': typeof InstellingenRoute
  '/klanten': typeof KlantenRoute
  '/login': typeof LoginRoute
  '/planning': typeof PlanningRoute
  '/printen': typeof PrintenRoute
  '/prullenbak': typeof PrullenbakRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/uitnodiging': typeof UitnodigingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dag': typeof DagRoute
  '/importeren': typeof ImporterenRoute
  '/instellingen': typeof InstellingenRoute
  '/klanten': typeof KlantenRoute
  '/login': typeof LoginRoute
  '/planning': typeof PlanningRoute
  '/printen': typeof PrintenRoute
  '/prullenbak': typeof PrullenbakRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/uitnodiging': typeof UitnodigingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dag'
    | '/importeren'
    | '/instellingen'
    | '/klanten'
    | '/login'
    | '/planning'
    | '/printen'
    | '/prullenbak'
    | '/signup'
    | '/team'
    | '/uitnodiging'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dag'
    | '/importeren'
    | '/instellingen'
    | '/klanten'
    | '/login'
    | '/planning'
    | '/printen'
    | '/prullenbak'
    | '/signup'
    | '/team'
    | '/uitnodiging'
  id:
    | '__root__'
    | '/'
    | '/dag'
    | '/importeren'
    | '/instellingen'
    | '/klanten'
    | '/login'
    | '/planning'
    | '/printen'
    | '/prullenbak'
    | '/signup'
    | '/team'
    | '/uitnodiging'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DagRoute: typeof DagRoute
  ImporterenRoute: typeof ImporterenRoute
  InstellingenRoute: typeof InstellingenRoute
  KlantenRoute: typeof KlantenRoute
  LoginRoute: typeof LoginRoute
  PlanningRoute: typeof PlanningRoute
  PrintenRoute: typeof PrintenRoute
  PrullenbakRoute: typeof PrullenbakRoute
  SignupRoute: typeof SignupRoute
  TeamRoute: typeof TeamRoute
  UitnodigingRoute: typeof UitnodigingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dag': {
      id: '/dag'
      path: '/dag'
      fullPath: '/dag'
      preLoaderRoute: typeof DagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importeren': {
      id: '/importeren'
      path: '/importeren'
      fullPath: '/importeren'
      preLoaderRoute: typeof ImporterenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instellingen': {
      id: '/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof InstellingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klanten': {
      id: '/klanten'
      path: '/klanten'
      fullPath: '/klanten'
      preLoaderRoute: typeof KlantenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printen': {
      id: '/printen'
      path: '/printen'
      fullPath: '/printen'
      preLoaderRoute: typeof PrintenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prullenbak': {
      id: '/prullenbak'
      path: '/prullenbak'
      fullPath: '/prullenbak'
      preLoaderRoute: typeof PrullenbakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uitnodiging': {
      id: '/uitnodiging'
      path: '/uitnodiging'
      fullPath: '/uitnodiging'
      preLoaderRoute: typeof UitnodigingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DagRoute: DagRoute,
  ImporterenRoute: ImporterenRoute,
  InstellingenRoute: InstellingenRoute,
  KlantenRoute: KlantenRoute,
  LoginRoute: LoginRoute,
  PlanningRoute: PlanningRoute,
  PrintenRoute: PrintenRoute,
  PrullenbakRoute: PrullenbakRoute,
  SignupRoute: SignupRoute,
  TeamRoute: TeamRoute,
  UitnodigingRoute: UitnodigingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
