/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AanmeldenRouteImport } from './routes/aanmelden'
import { Route as AanmeldingenRouteImport } from './routes/aanmeldingen'
import { Route as BerichtenRouteImport } from './routes/berichten'
import { Route as BetalingenRouteImport } from './routes/betalingen'
import { Route as DagRouteImport } from './routes/dag'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ImporterenRouteImport } from './routes/importeren'
import { Route as InstellingenRouteImport } from './routes/instellingen'
import { Route as KlantenRouteImport } from './routes/klanten'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MailingRouteImport } from './routes/mailing'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PrintenRouteImport } from './routes/printen'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrullenbakRouteImport } from './routes/prullenbak'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StijlgidsRouteImport } from './routes/stijlgids'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UitnodigingRouteImport } from './routes/uitnodiging'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AanmeldenRoute = AanmeldenRouteImport.update({
  id: '/aanmelden',
  path: '/aanmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const AanmeldingenRoute = AanmeldingenRouteImport.update({
  id: '/aanmeldingen',
  path: '/aanmeldingen',
  getParentRoute: () => rootRouteImport,
} as any)
const BerichtenRoute = BerichtenRouteImport.update({
  id: '/berichten',
  path: '/berichten',
  getParentRoute: () => rootRouteImport,
} as any)
const BetalingenRoute = BetalingenRouteImport.update({
  id: '/betalingen',
  path: '/betalingen',
  getParentRoute: () => rootRouteImport,
} as any)
const DagRoute = DagRouteImport.update({
  id: '/dag',
  path: '/dag',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ImporterenRoute = ImporterenRouteImport.update({
  id: '/importeren',
  path: '/importeren',
  getParentRoute: () => rootRouteImport,
} as any)
const InstellingenRoute = InstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => rootRouteImport,
} as any)
const KlantenRoute = KlantenRouteImport.update({
  id: '/klanten',
  path: '/klanten',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MailingRoute = MailingRouteImport.update({
  id: '/mailing',
  path: '/mailing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintenRoute = PrintenRouteImport.update({
  id: '/printen',
  path: '/printen',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrullenbakRoute = PrullenbakRouteImport.update({
  id: '/prullenbak',
  path: '/prullenbak',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StijlgidsRoute = StijlgidsRouteImport.update({
  id: '/stijlgids',
  path: '/stijlgids',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UitnodigingRoute = UitnodigingRouteImport.update({
  id: '/uitnodiging',
  path: '/uitnodiging',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/aanmeldingen': typeof AanmeldingenRoute
  '/berichten': typeof BerichtenRoute
  '/betalingen': typeof BetalingenRoute
  '/dag': typeof DagRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/importeren': typeof ImporterenRoute
  '/instellingen': typeof InstellingenRoute
  '/klanten': typeof KlantenRoute
  '/login': typeof LoginRoute
  '/mailing': typeof MailingRoute
  '/planning': typeof PlanningRoute
  '/printen': typeof PrintenRoute
  '/privacy': typeof PrivacyRoute
  '/prullenbak': typeof PrullenbakRoute
  '/signup': typeof SignupRoute
  '/stijlgids': typeof StijlgidsRoute
  '/team': typeof TeamRoute
  '/uitnodiging': typeof UitnodigingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/aanmeldingen': typeof AanmeldingenRoute
  '/berichten': typeof BerichtenRoute
  '/betalingen': typeof BetalingenRoute
  '/dag': typeof DagRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/importeren': typeof ImporterenRoute
  '/instellingen': typeof InstellingenRoute
  '/klanten': typeof KlantenRoute
  '/login': typeof LoginRoute
  '/mailing': typeof MailingRoute
  '/planning': typeof PlanningRoute
  '/printen': typeof PrintenRoute
  '/privacy': typeof PrivacyRoute
  '/prullenbak': typeof PrullenbakRoute
  '/signup': typeof SignupRoute
  '/stijlgids': typeof StijlgidsRoute
  '/team': typeof TeamRoute
  '/uitnodiging': typeof UitnodigingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/aanmeldingen': typeof AanmeldingenRoute
  '/berichten': typeof BerichtenRoute
  '/betalingen': typeof BetalingenRoute
  '/dag': typeof DagRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/importeren': typeof ImporterenRoute
  '/instellingen': typeof InstellingenRoute
  '/klanten': typeof KlantenRoute
  '/login': typeof LoginRoute
  '/mailing': typeof MailingRoute
  '/planning': typeof PlanningRoute
  '/printen': typeof PrintenRoute
  '/privacy': typeof PrivacyRoute
  '/prullenbak': typeof PrullenbakRoute
  '/signup': typeof SignupRoute
  '/stijlgids': typeof StijlgidsRoute
  '/team': typeof TeamRoute
  '/uitnodiging': typeof UitnodigingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aanmelden'
    | '/aanmeldingen'
    | '/berichten'
    | '/betalingen'
    | '/dag'
    | '/dashboard'
    | '/home'
    | '/importeren'
    | '/instellingen'
    | '/klanten'
    | '/login'
    | '/mailing'
    | '/planning'
    | '/printen'
    | '/privacy'
    | '/prullenbak'
    | '/signup'
    | '/stijlgids'
    | '/team'
    | '/uitnodiging'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aanmelden'
    | '/aanmeldingen'
    | '/berichten'
    | '/betalingen'
    | '/dag'
    | '/dashboard'
    | '/home'
    | '/importeren'
    | '/instellingen'
    | '/klanten'
    | '/login'
    | '/mailing'
    | '/planning'
    | '/printen'
    | '/privacy'
    | '/prullenbak'
    | '/signup'
    | '/stijlgids'
    | '/team'
    | '/uitnodiging'
  id:
    | '__root__'
    | '/'
    | '/aanmelden'
    | '/aanmeldingen'
    | '/berichten'
    | '/betalingen'
    | '/dag'
    | '/dashboard'
    | '/home'
    | '/importeren'
    | '/instellingen'
    | '/klanten'
    | '/login'
    | '/mailing'
    | '/planning'
    | '/printen'
    | '/privacy'
    | '/prullenbak'
    | '/signup'
    | '/stijlgids'
    | '/team'
    | '/uitnodiging'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AanmeldenRoute: typeof AanmeldenRoute
  AanmeldingenRoute: typeof AanmeldingenRoute
  BerichtenRoute: typeof BerichtenRoute
  BetalingenRoute: typeof BetalingenRoute
  DagRoute: typeof DagRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  ImporterenRoute: typeof ImporterenRoute
  InstellingenRoute: typeof InstellingenRoute
  KlantenRoute: typeof KlantenRoute
  LoginRoute: typeof LoginRoute
  MailingRoute: typeof MailingRoute
  PlanningRoute: typeof PlanningRoute
  PrintenRoute: typeof PrintenRoute
  PrivacyRoute: typeof PrivacyRoute
  PrullenbakRoute: typeof PrullenbakRoute
  SignupRoute: typeof SignupRoute
  StijlgidsRoute: typeof StijlgidsRoute
  TeamRoute: typeof TeamRoute
  UitnodigingRoute: typeof UitnodigingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanmelden': {
      id: '/aanmelden'
      path: '/aanmelden'
      fullPath: '/aanmelden'
      preLoaderRoute: typeof AanmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanmeldingen': {
      id: '/aanmeldingen'
      path: '/aanmeldingen'
      fullPath: '/aanmeldingen'
      preLoaderRoute: typeof AanmeldingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berichten': {
      id: '/berichten'
      path: '/berichten'
      fullPath: '/berichten'
      preLoaderRoute: typeof BerichtenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betalingen': {
      id: '/betalingen'
      path: '/betalingen'
      fullPath: '/betalingen'
      preLoaderRoute: typeof BetalingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dag': {
      id: '/dag'
      path: '/dag'
      fullPath: '/dag'
      preLoaderRoute: typeof DagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importeren': {
      id: '/importeren'
      path: '/importeren'
      fullPath: '/importeren'
      preLoaderRoute: typeof ImporterenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instellingen': {
      id: '/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof InstellingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klanten': {
      id: '/klanten'
      path: '/klanten'
      fullPath: '/klanten'
      preLoaderRoute: typeof KlantenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailing': {
      id: '/mailing'
      path: '/mailing'
      fullPath: '/mailing'
      preLoaderRoute: typeof MailingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printen': {
      id: '/printen'
      path: '/printen'
      fullPath: '/printen'
      preLoaderRoute: typeof PrintenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prullenbak': {
      id: '/prullenbak'
      path: '/prullenbak'
      fullPath: '/prullenbak'
      preLoaderRoute: typeof PrullenbakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stijlgids': {
      id: '/stijlgids'
      path: '/stijlgids'
      fullPath: '/stijlgids'
      preLoaderRoute: typeof StijlgidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uitnodiging': {
      id: '/uitnodiging'
      path: '/uitnodiging'
      fullPath: '/uitnodiging'
      preLoaderRoute: typeof UitnodigingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AanmeldenRoute: AanmeldenRoute,
  AanmeldingenRoute: AanmeldingenRoute,
  BerichtenRoute: BerichtenRoute,
  BetalingenRoute: BetalingenRoute,
  DagRoute: DagRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  ImporterenRoute: ImporterenRoute,
  InstellingenRoute: InstellingenRoute,
  KlantenRoute: KlantenRoute,
  LoginRoute: LoginRoute,
  MailingRoute: MailingRoute,
  PlanningRoute: PlanningRoute,
  PrintenRoute: PrintenRoute,
  PrivacyRoute: PrivacyRoute,
  PrullenbakRoute: PrullenbakRoute,
  SignupRoute: SignupRoute,
  StijlgidsRoute: StijlgidsRoute,
  TeamRoute: TeamRoute,
  UitnodigingRoute: UitnodigingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
