/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImporterenRouteImport } from './routes/importeren'
import { Route as PrintenRouteImport } from './routes/printen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImporterenRoute = ImporterenRouteImport.update({
  id: '/importeren',
  path: '/importeren',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintenRoute = PrintenRouteImport.update({
  id: '/printen',
  path: '/printen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/importeren': typeof ImporterenRoute
  '/printen': typeof PrintenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/importeren': typeof ImporterenRoute
  '/printen': typeof PrintenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/importeren': typeof ImporterenRoute
  '/printen': typeof PrintenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/importeren' | '/printen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/importeren' | '/printen'
  id: '__root__' | '/' | '/importeren' | '/printen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImporterenRoute: typeof ImporterenRoute
  PrintenRoute: typeof PrintenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importeren': {
      id: '/importeren'
      path: '/importeren'
      fullPath: '/importeren'
      preLoaderRoute: typeof ImporterenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printen': {
      id: '/printen'
      path: '/printen'
      fullPath: '/printen'
      preLoaderRoute: typeof PrintenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImporterenRoute: ImporterenRoute,
  PrintenRoute: PrintenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
